<a href="https://colab.research.google.com/github/Parth354/ML_Models/blob/main/Artificial_Neural_Network(ANN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


### **Artificial Neural Network**

Importing the Libraries

In [30]:
import numpy as np
import tensorflow as tf
import pandas as pd

### **Part 1:  Data Preprocessing**


Importing the Dataset

In [31]:
dataset=pd.read_csv("Churn_Modelling.csv")
X=dataset.iloc[:,3:-1].values
Y=dataset.iloc[:,-1].values

In [32]:
print(X)
print(Y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


Encoding the Categorical Data

In [33]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Performing One Hot Encoding for the Country Data

In [34]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder="passthrough")
X=np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the Data into Test Train sets

In [36]:
from sklearn.model_selection import train_test_split
X_train , X_test, Y_train , Y_test = train_test_split( X ,Y, test_size=0.2, random_state=0)

Feature Scaling(Always Apply in Deep Learning)


In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

### **Part 2: Building the ANN Model**

Intializing the ANN

In [38]:
ann= tf.keras.models.Sequential()

Adding The Input Layer and The First Hidden Layer

In [39]:
ann.add(tf.keras.layers.Dense(units = 6 ,activation ="relu" ))

Adding the Second Hidden Layer

In [40]:
ann.add(tf.keras.layers.Dense(units = 6 ,activation ="relu" ))

Adding the Output Layer

In [41]:
ann.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid" ))

### **Part 3: Training the ANN**

Compiling the ANN

In [42]:
ann.compile(optimizer= "adam" , loss= "binary_crossentropy" , metrics = ['accuracy'])

Trainning the ANN on the Training Set

In [43]:
ann.fit(X_train,Y_train , batch_size=32, epochs =100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5879 - accuracy: 0.7175
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4881 - accuracy: 0.8006
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4583 - accuracy: 0.8014
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4353 - accuracy: 0.8020
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4217 - accuracy: 0.8106
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4121 - accuracy: 0.8142
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4040 - accuracy: 0.8229
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3963 - accuracy: 0.8256
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3882 - accuracy: 0.8326
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3816 - accura

### **Part 4 : Making the Predications and Evaluating the Model**

Predicting The Result Of Single Observation

In [52]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))

1/1 [==============================] - 0s 19ms/step
[[0.01892288]]


Predicting the Test Set Results

In [56]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making The Confusison Matrix

In [58]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test,y_pred)

[[1517   78]
 [ 197  208]]


0.8625